// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA42gb0xKLoBIY1ybOerGM0IUy6aMwRN-g',
    appId: '1:490307536547:web:fa76064a9a403b742c2116',
    messagingSenderId: '490307536547',
    projectId: 'chat-app-by-ac',
    authDomain: 'chat-app-by-ac.firebaseapp.com',
    storageBucket: 'chat-app-by-ac.firebasestorage.app',
    measurementId: 'G-EP8HZYLB2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1y-xDMevG6attPDW8hRzYZGW4ckdnyA',
    appId: '1:490307536547:android:e6657a5b83aeb2182c2116',
    messagingSenderId: '490307536547',
    projectId: 'chat-app-by-ac',
    storageBucket: 'chat-app-by-ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzyMSYWfzKA7nrzXT0IxNfeCP4Bynruo',
    appId: '1:490307536547:ios:9637d7c8631a7e9f2c2116',
    messagingSenderId: '490307536547',
    projectId: 'chat-app-by-ac',
    storageBucket: 'chat-app-by-ac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzyMSYWfzKA7nrzXT0IxNfeCP4Bynruo',
    appId: '1:490307536547:ios:9637d7c8631a7e9f2c2116',
    messagingSenderId: '490307536547',
    projectId: 'chat-app-by-ac',
    storageBucket: 'chat-app-by-ac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA42gb0xKLoBIY1ybOerGM0IUy6aMwRN-g',
    appId: '1:490307536547:web:be235f9cbbdd8b5b2c2116',
    messagingSenderId: '490307536547',
    projectId: 'chat-app-by-ac',
    authDomain: 'chat-app-by-ac.firebaseapp.com',
    storageBucket: 'chat-app-by-ac.firebasestorage.app',
    measurementId: 'G-X9DH19ZT4F',
  );
}
